version: '3'
services:
  dcapi:
    container_name: dcapi
    build: ./dcapi
    ports:
      - "9011:7001"
    volumes:
      - ./dcapi:/usr/src/app
      # - ./logs:/usr/src/app/logs
    depends_on:
      - db
    command: "npm run docker"
    # stdin_open: true
    # tty: true


  db:
    container_name: dcdb
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: 'digicash'
      # MYSQL_DATABASE: 'digicash'
      # MYSQL_USER: 'digicash'
      # MYSQL_PASSWORD: 'digicash'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'digicash'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "9012:3306"