version: '3'
services:
  dcapi:
    # container_name: dcapi
    # build: ./dcapi
    image: dcapi
    ports:
      - "9011:7001"
    networks:
      - webnet
    volumes:
      # - ./dcapi:/usr/src/app
      - /data/code/github/fishjar/digicashlab/logs:/usr/src/app/logs
    depends_on:
      - db
    deploy:
    #   # replicas: 1
    #   # resources:
    #   #   limits:
    #   #     cpus: '0.25'
    #   #     memory: 200M
    #     # reservations:
    #     #   cpus: '0.25'
    #     #   memory: 50M
      restart_policy:
        condition: on-failure
    command: bash -c "sleep 30 && NODE_ENV=production npm run migrate:up && EGG_SERVER_ENV=prod npm run docker"

  dcweb:
    # container_name: dcweb
    image: dcweb
    # build: ./dcweb
    ports:
      - "9013:5000"
    networks:
      - webnet
    depends_on:
      - dcapi
    deploy:
    #   # replicas: 1
    #   # resources:
    #   #   limits:
    #   #     cpus: '0.25'
    #   #     memory: 75M
    #     # reservations:
    #     #   cpus: '0.25'
    #     #   memory: 25M
      restart_policy:
        condition: on-failure
  db:
    # container_name: dcdb
    image: mysql:latest
    volumes:
      - /data/code/github/fishjar/digicashlab/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'digicash'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "9012:3306"
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
      # resources:
      #   limits:
      #     cpus: '0.25'
      #     memory: 400M
        # reservations:
        #   cpus: '0.25'
        #   memory: 100M
      # restart_policy:
      #   condition: on-failure
networks:
  webnet: